"""(PromoCode): code indexed, add img_source

Revision ID: 2202e148f390
Revises: 7df2c2bcaa12
Create Date: 2023-12-06 01:55:17.630977

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2202e148f390"
down_revision: Union[str, None] = "7df2c2bcaa12"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promo_codes", sa.Column("img_source", sa.String(), nullable=True))
    op.drop_constraint("promo_codes_code_key", "promo_codes", type_="unique")
    op.create_index(op.f("ix_promo_codes_code"), "promo_codes", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promo_codes_code"), table_name="promo_codes")
    op.create_unique_constraint("promo_codes_code_key", "promo_codes", ["code"])
    op.drop_column("promo_codes", "img_source")
    # ### end Alembic commands ###
