"""add cities

Revision ID: b9c292239722
Revises: 0487f0685ff7
Create Date: 2023-11-14 00:20:18.871941

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'b9c292239722'
down_revision: Union[str, None] = '0487f0685ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
