"""Create database

Revision ID: 776fc88b7567
Revises: 
Create Date: 2023-10-24 22:44:59.924234

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "776fc88b7567"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
