"""add user_adreses

Revision ID: 6e19ba729787
Revises: b9c292239722
Create Date: 2023-11-14 00:23:12.108095

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '6e19ba729787'
down_revision: Union[str, None] = 'b9c292239722'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
