"""add verification code table

Revision ID: 1344838eec02
Revises: b9409e71a97d
Create Date: 2023-11-27 17:26:55.029096

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1344838eec02"
down_revision: Union[str, None] = "b9409e71a97d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expiration_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_codes_code"),
        "verification_codes",
        ["code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_codes_id"),
        "verification_codes",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verification_codes_id"), table_name="verification_codes")
    op.drop_index(op.f("ix_verification_codes_code"), table_name="verification_codes")
    op.drop_table("verification_codes")
    # ### end Alembic commands ###
