"""only admins in UserRole

Revision ID: 10453e8b27dd
Revises: b1d535c5c8df
Create Date: 2023-12-11 03:27:28.878683

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "10453e8b27dd"
down_revision: Union[str, None] = "b1d535c5c8df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
