"""secret instead of code in VerificationCode table

Revision ID: 24e9ddae6e90
Revises: 6161966d6f23
Create Date: 2023-11-29 11:33:35.404237

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24e9ddae6e90"
down_revision: Union[str, None] = "6161966d6f23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("verification_codes", sa.Column("secret", sa.String(), nullable=True))
    op.drop_index("ix_verification_codes_code", table_name="verification_codes")
    op.drop_column("verification_codes", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "verification_codes",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_verification_codes_code",
        "verification_codes",
        ["code"],
        unique=False,
    )
    op.drop_column("verification_codes", "secret")
    # ### end Alembic commands ###
