"""add img_source to Pizzas

Revision ID: b1d535c5c8df
Revises: a811ec57c2a8
Create Date: 2023-12-06 17:38:04.432505

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1d535c5c8df"
down_revision: Union[str, None] = "a811ec57c2a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pizzas", sa.Column("img_source", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pizzas", "img_source")
    # ### end Alembic commands ###
