"""telephone is string now

Revision ID: b9409e71a97d
Revises: 981be90b1365
Create Date: 2023-11-21 18:24:34.717102

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9409e71a97d"
down_revision: Union[str, None] = "981be90b1365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "telephone",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "telephone",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
