"""email instead of telephone

Revision ID: a7a0ede35f06
Revises: 1344838eec02
Create Date: 2023-11-27 20:24:03.928993

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7a0ede35f06"
down_revision: Union[str, None] = "1344838eec02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.drop_column("users", "telephone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("telephone", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "email")
    # ### end Alembic commands ###
